/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View, Button } from 'react-native';
import CBCarolWidget from 'react-native-carol-widget';

export default class App extends Component<{}> {
  _openCamera() {
    CBCarolWidget.onClick();
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆CBCarolWidget example☆</Text>
        <Text style={styles.instructions}>STATUS: loaded</Text>
        <Text style={styles.welcome}>☆☆☆</Text>
          <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
            <Button onPress={this._openCamera} title="Open Camera" />
          </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
